import 'dart:convert';
import 'dart:typed_data';

const Map<String, String> _encodedImageFixtures = {
  'jpg':
      '/9j/4AAQSkZJRgABAQAAAAAAAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAADAAIDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACP/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAVAQEBAAAAAAAAAAAAAAAAAAAHCf/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ADoDFU3/2Q==',
  'png':
      'iVBORw0KGgoAAAANSUhEUgAAAAIAAAADAQMAAACDJEzCAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAGUExURQCAAP///xQ/L08AAAABYktHRAH/Ai3eAAAAB3RJTUUH6gcOCAAvjDZVhgAAAAtJREFUCNdjYAABAAAGAAFm9MlsAAAAAElFTkSuQmCC',
  'gif':
      'R0lGODlhAgADAPAAAP8AAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQAAAAAACH/C0ltYWdlTWFnaWNrDmdhbW1hPTAuNDU0NTQ1ACwAAAAAAgADAAACAoRfACH5BAAKAAAAIf8LSW1hZ2VNYWdpY2sOZ2FtbWE9MC40NTQ1NDUALAAAAAACAAMAgAAA/wAAAAIChF8AOw==',
  'bmp':
      'Qk2iAAAAAAAAAIoAAAB8AAAAAgAAAAMAAAABABgAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAD/AAD/AAAAAAAA/0JHUnMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA/wAA/wAAAAD/AAD/AAAAAP8AAP8AAAAA',
  'webp':
      'UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoCAAMAAgA0JaACdLoAA5gA/vjdX/+Rx/+Rx/+Rx/8jj9SMMXMgAA==',
};

Uint8List imageFixture(String extension) => Uint8List.fromList(
      base64Decode(_encodedImageFixtures[extension]!),
    );

Iterable<String> get imageFixtureExtensions => _encodedImageFixtures.keys;
